# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/huykn/Desktop/gooseDB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/huykn/Desktop/gooseDB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/huykn/Desktop/gooseDB/CMakeFiles /Users/huykn/Desktop/gooseDB//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/huykn/Desktop/gooseDB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named http_tcp_linux

# Build rule for target.
http_tcp_linux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 http_tcp_linux
.PHONY : http_tcp_linux

# fast build rule for target.
http_tcp_linux/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_tcp_linux.dir/build.make CMakeFiles/http_tcp_linux.dir/build
.PHONY : http_tcp_linux/fast

#=============================================================================
# Target rules for targets named kvs_lib

# Build rule for target.
kvs_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kvs_lib
.PHONY : kvs_lib

# fast build rule for target.
kvs_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kvs_lib.dir/build.make CMakeFiles/kvs_lib.dir/build
.PHONY : kvs_lib/fast

#=============================================================================
# Target rules for targets named gooseDB

# Build rule for target.
gooseDB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gooseDB
.PHONY : gooseDB

# fast build rule for target.
gooseDB/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gooseDB.dir/build.make CMakeFiles/gooseDB.dir/build
.PHONY : gooseDB/fast

#=============================================================================
# Target rules for targets named gooseDB_server1

# Build rule for target.
gooseDB_server1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gooseDB_server1
.PHONY : gooseDB_server1

# fast build rule for target.
gooseDB_server1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gooseDB_server1.dir/build.make CMakeFiles/gooseDB_server1.dir/build
.PHONY : gooseDB_server1/fast

HTTP_/src/http_tcp_linux.o: HTTP_/src/http_tcp_linux.cc.o
.PHONY : HTTP_/src/http_tcp_linux.o

# target to build an object file
HTTP_/src/http_tcp_linux.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_tcp_linux.dir/build.make CMakeFiles/http_tcp_linux.dir/HTTP_/src/http_tcp_linux.cc.o
.PHONY : HTTP_/src/http_tcp_linux.cc.o

HTTP_/src/http_tcp_linux.i: HTTP_/src/http_tcp_linux.cc.i
.PHONY : HTTP_/src/http_tcp_linux.i

# target to preprocess a source file
HTTP_/src/http_tcp_linux.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_tcp_linux.dir/build.make CMakeFiles/http_tcp_linux.dir/HTTP_/src/http_tcp_linux.cc.i
.PHONY : HTTP_/src/http_tcp_linux.cc.i

HTTP_/src/http_tcp_linux.s: HTTP_/src/http_tcp_linux.cc.s
.PHONY : HTTP_/src/http_tcp_linux.s

# target to generate assembly for a file
HTTP_/src/http_tcp_linux.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_tcp_linux.dir/build.make CMakeFiles/http_tcp_linux.dir/HTTP_/src/http_tcp_linux.cc.s
.PHONY : HTTP_/src/http_tcp_linux.cc.s

kvs/src/kvs.o: kvs/src/kvs.cc.o
.PHONY : kvs/src/kvs.o

# target to build an object file
kvs/src/kvs.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kvs_lib.dir/build.make CMakeFiles/kvs_lib.dir/kvs/src/kvs.cc.o
.PHONY : kvs/src/kvs.cc.o

kvs/src/kvs.i: kvs/src/kvs.cc.i
.PHONY : kvs/src/kvs.i

# target to preprocess a source file
kvs/src/kvs.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kvs_lib.dir/build.make CMakeFiles/kvs_lib.dir/kvs/src/kvs.cc.i
.PHONY : kvs/src/kvs.cc.i

kvs/src/kvs.s: kvs/src/kvs.cc.s
.PHONY : kvs/src/kvs.s

# target to generate assembly for a file
kvs/src/kvs.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kvs_lib.dir/build.make CMakeFiles/kvs_lib.dir/kvs/src/kvs.cc.s
.PHONY : kvs/src/kvs.cc.s

src/gooseDB.o: src/gooseDB.cc.o
.PHONY : src/gooseDB.o

# target to build an object file
src/gooseDB.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gooseDB.dir/build.make CMakeFiles/gooseDB.dir/src/gooseDB.cc.o
.PHONY : src/gooseDB.cc.o

src/gooseDB.i: src/gooseDB.cc.i
.PHONY : src/gooseDB.i

# target to preprocess a source file
src/gooseDB.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gooseDB.dir/build.make CMakeFiles/gooseDB.dir/src/gooseDB.cc.i
.PHONY : src/gooseDB.cc.i

src/gooseDB.s: src/gooseDB.cc.s
.PHONY : src/gooseDB.s

# target to generate assembly for a file
src/gooseDB.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gooseDB.dir/build.make CMakeFiles/gooseDB.dir/src/gooseDB.cc.s
.PHONY : src/gooseDB.cc.s

src/gooseDB_server1.o: src/gooseDB_server1.cc.o
.PHONY : src/gooseDB_server1.o

# target to build an object file
src/gooseDB_server1.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gooseDB_server1.dir/build.make CMakeFiles/gooseDB_server1.dir/src/gooseDB_server1.cc.o
.PHONY : src/gooseDB_server1.cc.o

src/gooseDB_server1.i: src/gooseDB_server1.cc.i
.PHONY : src/gooseDB_server1.i

# target to preprocess a source file
src/gooseDB_server1.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gooseDB_server1.dir/build.make CMakeFiles/gooseDB_server1.dir/src/gooseDB_server1.cc.i
.PHONY : src/gooseDB_server1.cc.i

src/gooseDB_server1.s: src/gooseDB_server1.cc.s
.PHONY : src/gooseDB_server1.s

# target to generate assembly for a file
src/gooseDB_server1.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gooseDB_server1.dir/build.make CMakeFiles/gooseDB_server1.dir/src/gooseDB_server1.cc.s
.PHONY : src/gooseDB_server1.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gooseDB"
	@echo "... gooseDB_server1"
	@echo "... http_tcp_linux"
	@echo "... kvs_lib"
	@echo "... HTTP_/src/http_tcp_linux.o"
	@echo "... HTTP_/src/http_tcp_linux.i"
	@echo "... HTTP_/src/http_tcp_linux.s"
	@echo "... kvs/src/kvs.o"
	@echo "... kvs/src/kvs.i"
	@echo "... kvs/src/kvs.s"
	@echo "... src/gooseDB.o"
	@echo "... src/gooseDB.i"
	@echo "... src/gooseDB.s"
	@echo "... src/gooseDB_server1.o"
	@echo "... src/gooseDB_server1.i"
	@echo "... src/gooseDB_server1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

